[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing for React Router
## Important: place file exceptions BEFORE the catch-all so they are served as-is.
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 

# Ensure correct headers for bots and browsers
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "all"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    X-Robots-Tag = "all"

# Cache policy: HTML always fresh
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache policy: hashed assets long-lived (Vite outputs /assets/* with content hash)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache policy: icons and static images
[[headers]]
  for = "/icon.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"